"""scripts/lint_repo.py: hard rule 5 (no real tailnet names or addresses) and no AI attribution
in commit messages. The repo itself must pass. Made-up "real" names below are split in two so
this file doesn't trip the lint it tests.
"""
from __future__ import annotations

import importlib.util
import io
import os
import subprocess
import sys
import tempfile
import unittest
from contextlib import redirect_stdout
from unittest import mock

from support import ROOT

SCRIPT = os.path.join(ROOT, "scripts", "lint_repo.py")


def load():
    sys.dont_write_bytecode = True  # no __pycache__ in scripts/
    spec = importlib.util.spec_from_file_location("lint_repo", SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


lint = load()
REAL_NAME = "devbox.cat-crocodile" + ".ts.net"
REAL_IP = "100.87." + "12.34"


class LeakTests(unittest.TestCase):
    def found(self, text, patterns=()):
        return [m for _, _, m in lint.leaks(text, patterns)]

    def test_example_names_pass(self):
        for text in ("http://hub-a.example.ts.net:8765", "HUB-A.example.ts.net", "<host>.<tailnet>.ts.net",
                     "hub2.tail1234.ts.net", "https%3A%2F%2Fhub.ts.net", "*.ts.net", "ts.net", "evil.ts.net"):
            self.assertEqual(self.found(text), [], text)

    def test_real_looking_names_fail(self):
        self.assertEqual(self.found("url = http://%s:8765" % REAL_NAME), [REAL_NAME])
        name = "my-mac.tail9f3a2" + ".ts.net"
        self.assertEqual(self.found(name), [name])

    def test_tailnet_addresses(self):
        for text in ("100.64.0.0/10", "100.101.102.103", "fd7a:115c:a1e0::/48", "[fd7a:115c:a1e0::1]:8765",
                     "100.128.0.1", "100.63.255.255", "10.100.64.5.1", "version 100.80.1"):
            self.assertEqual(self.found(text), [], text)
        self.assertEqual(self.found("bind %s" % REAL_IP), [REAL_IP])
        addr = "fd7a:115c:" + "a1e0:ab12:cd34::5"
        self.assertEqual(self.found(addr), [addr])

    def test_local_patterns(self):
        import re
        self.assertEqual(self.found("ssh someone@build-box-7", [re.compile(r"build-box-\d+")]), ["build-box-7"])

    def test_local_pattern_file(self):
        with tempfile.TemporaryDirectory() as d:
            path = os.path.join(d, "leak-patterns")
            with open(path, "w") as fh:
                fh.write("# comment\n\nacme-internal\n")
            with mock.patch.dict(os.environ, {"NEEDS_YOU_LEAK_PATTERNS": path}):
                pats = lint.local_patterns()
        self.assertEqual([p.pattern for p in pats], ["acme-internal"])


class AttributionTests(unittest.TestCase):
    def test_flags_trailers_and_generated_lines(self):
        msg = ("hub: fix x\n\nBody text about a generated with flag.\n\n"
               "Co-Authored-By: Someone <a@example.com>\n\U0001F916 Generated with [Tool](https://example.com)\n"
               "co-authored-by:x\n")
        self.assertEqual(len(lint.attribution(msg)), 3)

    def test_plain_messages_pass(self):
        self.assertEqual(lint.attribution("cli: the outbox is generated by flush\n\nGenerated files are committed."), [])
        self.assertEqual(lint.attribution("site: rebuild guides\n\nThe pages are generated from docs/."), [])


class CommitRangeTests(unittest.TestCase):
    def git(self, *args):
        subprocess.run(["git", "-C", self.dir] + list(args), check=True, stdout=subprocess.DEVNULL,
                       stderr=subprocess.DEVNULL)

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.dir = self.tmp.name
        self.git("init", "-q", "-b", "main")
        self.git("config", "user.email", "dev@example.com")
        self.git("config", "user.name", "Dev")
        with open(os.path.join(self.dir, "a.txt"), "w") as fh:
            fh.write("hello\n")
        self.git("add", "a.txt")
        self.git("commit", "-q", "-m", "first")
        self.git("checkout", "-q", "-b", "feature")

    def tearDown(self):
        self.tmp.cleanup()

    def run_lint(self, *args):
        out = io.StringIO()
        with mock.patch.object(lint, "ROOT", self.dir), mock.patch.dict(os.environ, {"NEEDS_YOU_LEAK_PATTERNS": "/nonexistent"}), \
                redirect_stdout(out):
            rc = lint.main(list(args))
        return rc, out.getvalue()

    def test_clean_branch_passes(self):
        self.git("commit", "-q", "--allow-empty", "-m", "docs: fix a typo")
        rc, out = self.run_lint("--base", "main")
        self.assertEqual(rc, 0, out)
        self.assertIn("1 commit(s) since main", out)

    def test_attribution_fails(self):
        self.git("commit", "-q", "--allow-empty", "-m", "x\n\nCo-Authored-By: Bot <bot@example.com>")
        rc, out = self.run_lint("--base", "main")
        self.assertEqual(rc, 1, out)
        self.assertIn("attribution", out)

    def test_hostname_in_message_fails(self):
        self.git("commit", "-q", "--allow-empty", "-m", "fix for %s" % REAL_NAME)
        rc, out = self.run_lint("--base", "main")
        self.assertEqual(rc, 1, out)

    def test_none_skips_commits(self):
        self.git("commit", "-q", "--allow-empty", "-m", "x\n\nCo-Authored-By: Bot <bot@example.com>")
        rc, out = self.run_lint("--base", "none")
        self.assertEqual(rc, 0, out)
        self.assertIn("not checked", out)

    def test_api_doc_without_tests_warns(self):
        os.makedirs(os.path.join(self.dir, "docs"))
        with open(os.path.join(self.dir, "docs", "API.md"), "w") as fh:
            fh.write("# API\n")
        self.git("add", "docs/API.md")
        self.git("commit", "-q", "-m", "docs: API")
        rc, out = self.run_lint("--base", "main")
        self.assertEqual(rc, 0, out)
        self.assertIn("warning: docs/API.md changed", out)

    def test_leaking_file_fails(self):
        with open(os.path.join(self.dir, "b.txt"), "w") as fh:
            fh.write("hub = http://%s:8765\n" % REAL_NAME)
        rc, out = self.run_lint("--base", "none")
        self.assertEqual(rc, 1, out)
        self.assertIn("b.txt:1: tailnet name", out)


class RepoTests(unittest.TestCase):
    def test_repo_has_no_tailnet_names_or_addresses(self):
        # Built-in rules only: a contributor's local denylist doesn't decide whether CI passes.
        out = io.StringIO()
        with redirect_stdout(out):
            bad = lint.check_files([])
        self.assertEqual(bad, 0, out.getvalue())


if __name__ == "__main__":
    unittest.main()
